### ISSUE TITLE
docker error appears during startup

### ISSUE THREAD

**Issue by joshsgoldstein** [sidprobstein/swirl-search#46]
swirl-15-f-app-1  | Error: .swirl not found, exiting
swirl-15-f-app-1  | Command stop reported an error

**Comment by sidprobstein** [comment]
@joshsgoldstein this is ok actually, but will suppress the error message in future

**Comment by sidprobstein** [comment]
Scheduled for post 1.7

**Comment by sidprobstein** [comment]
Fixed in 1.8

ss18f-app-1  | Collecting Statics:
ss18f-app-1  | 
ss18f-app-1  | 
ss18f-app-1  | 178 static files copied to '/app/static'.
ss18f-app-1  | 
ss18f-app-1  | Ok
ss18f-app-1  | Command successful!
ss18f-app-1  | __S_W_I_R_L__1_._8______________________________________________________________
ss18f-app-1  | 
ss18f-app-1  | Warning: logs directory does not exist, creating it
ss18f-app-1  | Start: rabbitmq -> rabbitmq-server ... Ok, pid: 32
ss18f-app-1  | Start: celery-worker -> celery -A swirl_server worker ... Ok, pid: 367
ss18f-app-1  | Start: celery-beats -> celery -A swirl_server beat --scheduler django_celery_beat.schedulers:DatabaseScheduler ... Ok, pid: 379
ss18f-app-1  | Updating .swirl... Ok
ss18f-app-1  | 
ss18f-app-1  |   PID TTY          TIME CMD
ss18f-app-1  |    32 ?        00:00:00 rabbitmq-server
ss18f-app-1  |   367 ?        00:00:05 celery
ss18f-app-1  |   379 ?        00:00:03 celery
ss18f-app-1  | 
ss18f-app-1  | Command successful!
ss18f-app-1  | 2023-01-15 17:34:46,033 INFO     Starting server at tcp:port=8000:interface=0.0.0.0
ss18f-app-1  | 2023-01-15 17:34:46,034 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
ss18f-app-1  | 2023-01-15 17:34:46,034 INFO     Configuring endpoint tcp:port=8000:interface=0.0.0.0
ss18f-app-1  | 2023-01-15 17:34:46,035 INFO     Listening on TCP address 0.0.0.0:8000
ss18f-app-1  | Forbidden: /swirl/searchproviders/
ss18f-app-1  | 2023-01-15 17:37:05,909 WARNING  Forbidden: /swirl/searchproviders/
ss18f-app-1  | 2023-01-15 17:37:31,303 INFO     views.py: Search.list()!
ss18f-app-1  | 2023-01-15 17:37:33,523 INFO     views.py: Search.create() from ?q
ss18f-app-1  | 2023-01-15 17:37:40,618 INFO     views.py: Calling mixer from ?search_id
